version: '3.9'
services:
  dash-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: henriquesena/painel-web:1.0.0
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"
    container_name: painel-web
    command: ["npm", "run", "start"]
