version: '3.9'
services:
  avantio-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: henriquesena/painel-server:1.0.0
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "9090:9090"
    container_name: painel-server
    command: ["npm", "run", "start:prod"]
